### PR TITLE
update aldeed packages

### PR DESCRIPTION
**Pull request by dapathy**
Migrate to the new collection2-core and node-simple-schema packages along with the necessary changes.  These packages have replaced the existing collection2 and meteor-simple-schema.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
That seems suspiciously easy. 😆

**Comment by copleykj** [comment]
If I remember correctly we will need the packages for denyUpdate and index functionality as well

**Comment by dapathy** [comment]
I was thinking that the individual packages that need them could import them, but maybe it's easier just to include them here.

**Comment by copleykj** [comment]
I think that's a good idea since most of the packages require them, and their inclusion was the default​ previously.

**Comment by dapathy** [comment]
Okeydoke

**Comment by copleykj** [comment]
I've just merged these manually into the devel branch. Thank you for the PR.

**Comment by dapathy** [comment]
Sounds great, thank you.

**Pull request merged**
