### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Most notable is the update to collection-hooks v1.

### CODE REVIEW

**Comment by StorytellerCZ** [comment]
Just notice that in production this package is pretty heavy due to underscore being part of it. Maybe Collections 2 v 3.0.2 could help here:
```
3.0.2

You can now update to raix:eventemitter@1.0.0 to potentially eliminate your app's dependency on the underscore package. meteor add raix:eventemitter@1.0.0
```

**Comment by StorytellerCZ** [comment]
Updated `collection-hooks` with new version and added funding file for @copleykj based on the readme.

**Comment by StorytellerCZ** [comment]
@copleykj Please check this PR, updating dependencies is getting more urgent for me.

**Comment by copleykj** [comment]
This seems good. I'll try to give it a thorough review tonight and see about publishing it.

**Pull request merged**
